apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sleep
  name: sleep
  namespace: cka
spec:
  containers:
  - args:
    - sleep
    - "1000"
    image: busybox
    name: sleep
    env:
    - name: teste
      value: "true"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
